# Generated by Django 3.2.18 on 2023-05-09 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('league', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
        ),
        migrations.CreateModel(
            name='RankingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.player')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.ranking')),
            ],
        ),
        migrations.AddField(
            model_name='ranking',
            name='players',
            field=models.ManyToManyField(through='leagues.RankingScore', to='leagues.Player'),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_points', models.PositiveIntegerField()),
                ('away_points', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ManyToManyField(related_name='away_match_set', to='leagues.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ManyToManyField(related_name='home_match_set', to='leagues.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='leagues.league'),
        ),
        migrations.AddConstraint(
            model_name='rankingscore',
            constraint=models.UniqueConstraint(fields=('ranking', 'player'), name='unique_players_in_ranking'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('league', 'name'), name='unique_names_in_league'),
        ),
    ]
