# Generated by Django 3.2.18 on 2023-05-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_alter_rankingscore_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
    ]
