# Generated by Django 3.2.18 on 2023-05-11 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_auto_20230511_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
