# Generated by Django 3.2.18 on 2023-05-12 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_alter_match_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
