# Generated by Django 3.2.19 on 2023-07-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_period_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('league', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('league', 'slug'), name='unique_stage_slugs_in_league'),
        ),
    ]
