# Generated by Django 3.2.19 on 2023-07-14 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_auto_20230714_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.stage'),
        ),
    ]
