# Generated by Django 3.2.19 on 2023-07-22 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_match_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankingscore',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='rankingscore',
            name='unique_players_in_ranking',
        ),
    ]
