# Generated by Django 3.2.19 on 2023-07-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_auto_20230722_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='league',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='players',
        ),
        migrations.RemoveField(
            model_name='rankingscore',
            name='player',
        ),
        migrations.RemoveField(
            model_name='rankingscore',
            name='ranking',
        ),
    ]
