# Generated by Django 3.2.19 on 2023-07-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_auto_20230722_0618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranking',
        ),
        migrations.DeleteModel(
            name='RankingScore',
        ),
    ]
