# Generated by Django 3.2.19 on 2023-07-22 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_auto_20230722_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='RankingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, default=None, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.player')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.stage')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='ranking',
            field=models.ManyToManyField(through='leagues.RankingScore', to='leagues.Player'),
        ),
        migrations.AddConstraint(
            model_name='rankingscore',
            constraint=models.UniqueConstraint(fields=('stage', 'player'), name='unique_players_in_ranking'),
        ),
    ]
