# Generated by Django 3.2.19 on 2023-07-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_auto_20230722_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='previous',
            field=models.ManyToManyField(to='leagues.Stage'),
        ),
    ]
