# Generated by Django 3.2.19 on 2023-07-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_auto_20230726_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='previous',
            field=models.ManyToManyField(blank=True, null=True, to='leagues.Stage'),
        ),
    ]
