# Generated by Django 3.2.19 on 2023-07-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0018_auto_20230726_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='bonus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stage',
            name='bonus',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
