# Generated by Django 4.2.1 on 2023-07-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0019_auto_20230727_0738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order']},
        ),
    ]
