# Generated by Django 4.2.1 on 2023-08-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0020_alter_stage_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='previous',
            new_name='included',
        ),
    ]
