# Generated by Django 4.2.1 on 2023-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0023_league_write_key_league_write_protected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='write_key',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='league',
            constraint=models.CheckConstraint(check=models.Q(('write_protected', False), ('write_key__isnull', False), _connector='OR'), name='write_key_if_write_protected'),
        ),
    ]
