# Generated by Django 4.2.1 on 2023-08-05 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0024_alter_league_write_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.player')),
            ],
        ),
        migrations.CreateModel(
            name='AwayTeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leagues.player')),
            ],
        ),
    ]
