# Generated by Django 4.2.1 on 2023-08-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0026_auto_20230805_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_team',
        ),
    ]
