# Generated by Django 4.2.1 on 2023-08-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0027_remove_match_away_team_remove_match_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ManyToManyField(related_name='away_match_set', through='leagues.AwayTeamPlayer', to='leagues.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ManyToManyField(related_name='home_match_set', through='leagues.HomeTeamPlayer', to='leagues.player'),
        ),
    ]
