# Generated by Django 4.2.7 on 2024-03-23 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0029_alter_rankingscore_options_league_regularisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='regularisation',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
