# Generated by Django 4.2.7 on 2024-03-23 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0030_alter_league_regularisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='regularisation',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
