# Generated by Django 4.2.7 on 2024-04-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0032_league_points_to_win_stage_points_to_win'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankingscore',
            options={'ordering': ['-score', 'player__name', 'stage']},
        ),
    ]
