# Generated by Django 4.2.12 on 2024-07-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0035_alter_league_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='datetime_started',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
