# Generated by Django 4.2.12 on 2024-07-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0036_match_datetime_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='latest_matches_count',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='league',
            name='nextup_matches_count',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
