# Generated by Django 4.2.12 on 2024-08-02 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0037_league_latest_matches_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='dashboard_update_interval',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
