# Generated by Django 4.2.12 on 2024-08-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0039_league_player_selection_key_player_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
