# Generated by Django 4.2.18 on 2025-04-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0040_alter_league_options_player_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
