# Generated by Django 4.2.18 on 2025-04-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0041_match_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='on_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
