# Generated by Django 4.2.19 on 2025-05-14 15:28

from django.db import migrations, models
import leagues.models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0042_stage_on_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='player_selection_key',
            field=models.CharField(blank=True, default=leagues.models.create_key, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='write_key',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
