# Generated by Django 4.2.19 on 2025-05-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0043_alter_league_player_selection_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='periods',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='stage',
            name='periods',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
