# Generated by Django 4.2.19 on 2025-05-14 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0044_league_periods_stage_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='periods',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='stage',
            name='periods',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
