# Generated by Django 4.2.19 on 2025-05-14 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0045_alter_league_periods_alter_stage_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=50)),
                ('league', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('order'), descending=True, nulls_first=True)],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='court',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.court'),
        ),
        migrations.AddConstraint(
            model_name='court',
            constraint=models.UniqueConstraint(fields=('league', 'name'), name='unique_court_names_in_league'),
        ),
    ]
