# Generated by Django 4.2.19 on 2025-07-21 11:04

from django.db import migrations, models


def set_initial_order(apps, schema_editor):
    Match = apps.get_model('leagues', 'Match')
    League = apps.get_model('leagues', 'League')
    for league in League.objects.all():
        matches = Match.objects.filter(league=league).order_by("datetime")
        for (index, m) in enumerate(matches):
            m.order = index
            m.save()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0047_alter_match_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='match',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=42, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_initial_order,
            reverse_code=lambda apps, schema_editor: None
        ),
    ]
