# Generated by Django 4.2.23 on 2025-08-13 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0048_alter_match_options_match_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('league', 'uuid'), name='unique_match_uuid_in_league'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('league', 'uuid'), name='unique_player_uuid_in_league'),
        ),
    ]
