# Generated by Django 4.2.23 on 2025-08-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0049_alter_match_uuid_alter_player_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awayteamplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leagues.player'),
        ),
        migrations.AlterField(
            model_name='hometeamplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='leagues.player'),
        ),
    ]
