# Generated by Django 4.2.23 on 2025-08-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0050_alter_awayteamplayer_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score_raw',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
