# Generated by Django 4.2.23 on 2025-08-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0051_player_score_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingscore',
            name='score_raw',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
